import { dom, library, config } from "@fortawesome/fontawesome-svg-core";
import {
    faEraser,
    faPlus,
    faTrash,
    faEye,
    faEyeSlash,
    faFolderOpen,
    faArrowDown,
    faArrowUp,
    faArrowLeft,
    faArrowRight,
    faFloppyDisk,
    faMagnifyingGlass,
    faDeleteLeft,
    faPencil,
    faCircleInfo,
    faArrowRightToBracket,
    faCircleCheck,
    faCircleXmark,
    faBars,
    faXmark,
    faCrop,
    faWandMagic,
    faSyncAlt,
    faSearchPlus,
    faSearchMinus,
    faArrowsAltH,
    faArrowsAltV,
    faUndoAlt,
    faRedoAlt,
    faCircleArrowUp,
    faCircleArrowDown,
    faQuestionCircle,
    faBan,
    faCopy,
    faListUl,
    faChevronLeft,
    faChevronRight,
    faCheck,
    faCircleExclamation,
    faRankingStar,
    faGlobe,
} from "@fortawesome/free-solid-svg-icons";
import { faGithub } from "@fortawesome/free-brands-svg-icons";

config.autoReplaceSvg = false;
library.add(faEraser);
library.add(faPlus);
library.add(faTrash);
library.add(faEye);
library.add(faEyeSlash);
library.add(faFolderOpen);
library.add(faArrowDown);
library.add(faArrowUp);
library.add(faArrowLeft);
library.add(faArrowRight);
library.add(faArrowRightToBracket);
library.add(faFloppyDisk);
library.add(faMagnifyingGlass);
library.add(faDeleteLeft);
library.add(faPencil);
library.add(faCircleInfo);
library.add(faCircleCheck);
library.add(faCircleXmark);
library.add(faXmark);
library.add(faBars);
library.add(faCrop);
library.add(faWandMagic);
library.add(faSyncAlt);
library.add(faSearchPlus);
library.add(faSearchMinus);
library.add(faArrowLeft);
library.add(faArrowRight);
library.add(faCircleArrowUp);
library.add(faCircleArrowDown);
library.add(faArrowsAltH);
library.add(faArrowsAltV);
library.add(faUndoAlt);
library.add(faRedoAlt);
library.add(faQuestionCircle);
library.add(faBan);
library.add(faGithub);
library.add(faCopy);
library.add(faListUl);
library.add(faChevronLeft);
library.add(faChevronRight);
library.add(faCheck);
library.add(faCircleExclamation);
library.add(faRankingStar);
library.add(faGlobe);
dom.watch();
